2025-03-11 16:48:56,290 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:48:58,507 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:48:59,999 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:49:30,022 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:49:32,248 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:49:33,631 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:49:33,631 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:49:33,968 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:49:33,969 [INFO] USER:komal_agarwalla helper.py:658:check_lambda_name LOG: Validating lambda name: 'HelloWorld'
2025-03-11 16:49:33,970 [INFO] USER:komal_agarwalla helper.py:673:check_lambda_name LOG: Lambda name: 'HelloWorld' passed the validation
2025-03-11 16:49:33,970 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:49:33,970 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:49:33,971 [INFO] USER:komal_agarwalla generate.py:116:lambda_function LOG: Lambda names: ('HelloWorld',)
2025-03-11 16:49:33,971 [INFO] USER:komal_agarwalla generate.py:117:lambda_function LOG: Runtime: java
2025-03-11 16:49:33,971 [INFO] USER:komal_agarwalla generate.py:118:lambda_function LOG: Project path: C:/Users/komal_agarwalla/AWS/AWS/task03
2025-03-11 16:49:33,973 [INFO] USER:komal_agarwalla project.py:90:_generate_java_project_hierarchy LOG: Generating pom inside C:/Users/komal_agarwalla/AWS/AWS/task03
2025-03-11 16:49:33,975 [INFO] USER:komal_agarwalla project.py:95:_generate_java_project_hierarchy LOG: Pom file was generated by path: C:/Users/komal_agarwalla/AWS/AWS/task03\pom.xml
2025-03-11 16:49:33,996 [INFO] USER:komal_agarwalla lambda_function.py:374:_generate_java_lambdas LOG: Lambda HelloWorld created
2025-03-11 16:49:33,997 [INFO] USER:komal_agarwalla lambda_function.py:169:generate_lambda_function LOG: Lambda HelloWorld has been successfully added to the project.
2025-03-11 16:49:33,998 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage lambda_function, elapsed time: 0:00:00.027611
2025-03-11 16:50:30,715 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:50:32,937 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:50:34,213 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:50:34,213 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:50:34,591 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:50:34,592 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:50:34,593 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:50:34,594 [INFO] USER:komal_agarwalla base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'task3_api'
2025-03-11 16:50:34,594 [INFO] USER:komal_agarwalla base_generator.py:239:_validate_resource_name LOG: Resource name: 'task3_api' passed the validation
2025-03-11 16:50:34,594 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': set()}' inside with type 'api_gateway'
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '[]'
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:217:_find_file_with_duplicate LOG: No duplicated api_gateway with name 'task3_api' was found
2025-03-11 16:50:34,595 [INFO] USER:komal_agarwalla base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for api_gateway 'task3_api'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for api_gateway 'task3_api'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value 'api' for param 'deploy_stage'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'dependencies'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'resources'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-11 16:50:34,596 [INFO] USER:komal_agarwalla base_generator.py:202:write LOG: Writing deployment resources for api_gateway 'task3_api' to the file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:50:34,599 [INFO] USER:komal_agarwalla meta.py:264:api_gateway LOG: Api gateway 'task3_api' was added successfully
2025-03-11 16:50:34,599 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage api_gateway, elapsed time: 0:00:00.005706
2025-03-11 16:50:44,001 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:50:46,251 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:50:47,452 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:50:47,452 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:50:47,792 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:50:47,792 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:50:47,794 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:50:47,796 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:50:47,797 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:50:47,798 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:50:47,798 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:50:47,798 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:50:47,798 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:50:47,799 [INFO] USER:komal_agarwalla api_gateway_generator.py:180:write LOG: Adding resource '/hello' to api 'task3_api'...
2025-03-11 16:50:47,800 [INFO] USER:komal_agarwalla api_gateway_generator.py:201:write LOG: Adding resource '/hello' to api 'task3_api'...
2025-03-11 16:50:47,801 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 16:50:47,801 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object 'False' of the class '<class 'bool'>' for param 'enable_cors'
2025-03-11 16:50:47,802 [INFO] USER:komal_agarwalla meta.py:336:api_gateway_resource LOG: Resource '/hello' was added to API gateway 'task3_api' successfully
2025-03-11 16:50:47,803 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage api_gateway_resource, elapsed time: 0:00:00.007276
2025-03-11 16:50:59,240 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:51:01,474 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:51:03,346 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:51:03,346 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:51:03,760 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:51:03,761 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:51:03,761 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:51:03,763 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:51:03,764 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:51:03,764 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:51:03,764 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:51:03,764 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:51:03,764 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:51:03,765 [INFO] USER:komal_agarwalla api_gateway_generator.py:53:get_meta_with_resource LOG: Found resource '/hello' in api 'task3_api' in file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:51:03,765 [INFO] USER:komal_agarwalla api_gateway_generator.py:258:write LOG: Adding method 'GET' to resource '/hello' to api 'task3_api'...
2025-03-11 16:51:03,765 [INFO] USER:komal_agarwalla base_generator.py:115:_validate_lambda_existence LOG: Validating existence of lambda: hello_world
2025-03-11 16:51:03,765 [ERROR] USER:komal_agarwalla base_generator.py:119:_validate_lambda_existence LOG: Validation error: Lambda 'hello_world' wasn't found
2025-03-11 16:51:03,765 [ERROR] USER:komal_agarwalla decorators.py:136:wrapper LOG: Lambda 'hello_world' wasn't found
2025-03-11 16:51:03,792 [ERROR] USER:komal_agarwalla decorators.py:137:wrapper LOG: Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1106, in _generate
    generator.write()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 266, in write
    self._resolve_configuration()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 273, in _resolve_configuration
    self._validate_lambda_existence(lambda_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\base_generator.py", line 120, in _validate_lambda_existence
    raise ValueError(message)
ValueError: Lambda 'hello_world' wasn't found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 871, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 328, in timed
    result = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 385, in api_gateway_resource_method
    _generate(generator)
    ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1108, in _generate
    raise click.BadParameter(e)
click.exceptions.BadParameter: <exception str() failed>
Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1106, in _generate
    generator.write()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 266, in write
    self._resolve_configuration()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 273, in _resolve_configuration
    self._validate_lambda_existence(lambda_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\base_generator.py", line 120, in _validate_lambda_existence
    raise ValueError(message)
ValueError: Lambda 'hello_world' wasn't found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 871, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 328, in timed
    result = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 385, in api_gateway_resource_method
    _generate(generator)
    ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1108, in _generate
    raise click.BadParameter(e)
click.exceptions.BadParameter: <exception str() failed>
2025-03-11 16:51:39,434 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:51:41,642 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:51:42,948 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:51:42,948 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:51:43,289 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:51:43,290 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:51:43,291 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:51:43,292 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:51:43,293 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:51:43,293 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:51:43,294 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:51:43,294 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:51:43,294 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:51:43,294 [INFO] USER:komal_agarwalla api_gateway_generator.py:53:get_meta_with_resource LOG: Found resource '/hello' in api 'task3_api' in file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:51:43,294 [INFO] USER:komal_agarwalla api_gateway_generator.py:258:write LOG: Adding method 'GET' to resource '/hello' to api 'task3_api'...
2025-03-11 16:51:43,295 [INFO] USER:komal_agarwalla base_generator.py:115:_validate_lambda_existence LOG: Validating existence of lambda: hello_world
2025-03-11 16:51:43,295 [ERROR] USER:komal_agarwalla base_generator.py:119:_validate_lambda_existence LOG: Validation error: Lambda 'hello_world' wasn't found
2025-03-11 16:51:43,295 [ERROR] USER:komal_agarwalla decorators.py:136:wrapper LOG: Lambda 'hello_world' wasn't found
2025-03-11 16:51:43,300 [ERROR] USER:komal_agarwalla decorators.py:137:wrapper LOG: Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1106, in _generate
    generator.write()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 266, in write
    self._resolve_configuration()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 273, in _resolve_configuration
    self._validate_lambda_existence(lambda_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\base_generator.py", line 120, in _validate_lambda_existence
    raise ValueError(message)
ValueError: Lambda 'hello_world' wasn't found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 871, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 328, in timed
    result = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 385, in api_gateway_resource_method
    _generate(generator)
    ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1108, in _generate
    raise click.BadParameter(e)
click.exceptions.BadParameter: <exception str() failed>
Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1106, in _generate
    generator.write()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 266, in write
    self._resolve_configuration()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\api_gateway_generator.py", line 273, in _resolve_configuration
    self._validate_lambda_existence(lambda_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\generators\deployment_resources\base_generator.py", line 120, in _validate_lambda_existence
    raise ValueError(message)
ValueError: Lambda 'hello_world' wasn't found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 871, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\helper.py", line 328, in timed
    result = func(*args, **kwargs)
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 385, in api_gateway_resource_method
    _generate(generator)
    ~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\komal_agarwalla\AppData\Roaming\Python\Python313\site-packages\syndicate\core\groups\meta.py", line 1108, in _generate
    raise click.BadParameter(e)
click.exceptions.BadParameter: <exception str() failed>
2025-03-11 16:52:25,700 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:52:27,908 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:52:29,181 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:52:29,181 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:52:29,592 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:52:29,593 [INFO] USER:komal_agarwalla helper.py:658:check_lambda_name LOG: Validating lambda name: 'hello_world'
2025-03-11 16:52:29,593 [INFO] USER:komal_agarwalla helper.py:673:check_lambda_name LOG: Lambda name: 'hello_world' passed the validation
2025-03-11 16:52:29,593 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:52:29,594 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:52:29,594 [INFO] USER:komal_agarwalla generate.py:116:lambda_function LOG: Lambda names: ('hello_world',)
2025-03-11 16:52:29,595 [INFO] USER:komal_agarwalla generate.py:117:lambda_function LOG: Runtime: java
2025-03-11 16:52:29,595 [INFO] USER:komal_agarwalla generate.py:118:lambda_function LOG: Project path: C:/Users/komal_agarwalla/AWS/AWS/task03
2025-03-11 16:52:29,597 [INFO] USER:komal_agarwalla project.py:97:_generate_java_project_hierarchy LOG: Pom file inside C:/Users/komal_agarwalla/AWS/AWS/task03 already exists
2025-03-11 16:52:29,602 [INFO] USER:komal_agarwalla lambda_function.py:374:_generate_java_lambdas LOG: Lambda hello_world created
2025-03-11 16:52:29,603 [INFO] USER:komal_agarwalla lambda_function.py:169:generate_lambda_function LOG: Lambda hello_world has been successfully added to the project.
2025-03-11 16:52:29,603 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage lambda_function, elapsed time: 0:00:00.009250
2025-03-11 16:52:41,148 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:52:43,366 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:52:44,700 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:52:44,700 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:52:45,070 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:52:45,070 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:52:45,070 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:52:45,071 [INFO] USER:komal_agarwalla base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'task3_api'
2025-03-11 16:52:45,072 [INFO] USER:komal_agarwalla base_generator.py:239:_validate_resource_name LOG: Resource name: 'task3_api' passed the validation
2025-03-11 16:52:45,072 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:52:45,073 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:52:45,074 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:52:45,074 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:52:45,074 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:52:45,074 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:52:45,074 [WARNING] USER:komal_agarwalla base_generator.py:214:_find_file_with_duplicate LOG: Duplicated api_gateway with name 'task3_api' was found in: ['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']
2025-03-11 16:52:45,074 [WARNING] USER:komal_agarwalla base_generator.py:189:write LOG: Found duplicate while generating meta. Resource with name 'task3_api' was found in file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'.
2025-03-11 16:52:57,234 [WARNING] USER:komal_agarwalla base_generator.py:191:write LOG: Overwriting resource 'task3_api'
2025-03-11 16:52:57,235 [INFO] USER:komal_agarwalla base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for api_gateway 'task3_api'
2025-03-11 16:52:57,236 [INFO] USER:komal_agarwalla base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for api_gateway 'task3_api'
2025-03-11 16:52:57,236 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 16:52:57,236 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value 'api' for param 'deploy_stage'
2025-03-11 16:52:57,236 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'dependencies'
2025-03-11 16:52:57,236 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'resources'
2025-03-11 16:52:57,237 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-11 16:52:57,237 [INFO] USER:komal_agarwalla base_generator.py:202:write LOG: Writing deployment resources for api_gateway 'task3_api' to the file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:52:57,239 [INFO] USER:komal_agarwalla meta.py:264:api_gateway LOG: Api gateway 'task3_api' was added successfully
2025-03-11 16:52:57,239 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage api_gateway, elapsed time: 0:00:12.167802
2025-03-11 16:53:05,763 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:53:07,968 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:53:09,231 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:53:09,231 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:53:09,591 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:53:09,591 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:53:09,592 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:53:09,593 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:53:09,595 [INFO] USER:komal_agarwalla api_gateway_generator.py:180:write LOG: Adding resource '/hello' to api 'task3_api'...
2025-03-11 16:53:09,596 [INFO] USER:komal_agarwalla api_gateway_generator.py:201:write LOG: Adding resource '/hello' to api 'task3_api'...
2025-03-11 16:53:09,597 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 16:53:09,597 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object 'False' of the class '<class 'bool'>' for param 'enable_cors'
2025-03-11 16:53:09,598 [INFO] USER:komal_agarwalla meta.py:336:api_gateway_resource LOG: Resource '/hello' was added to API gateway 'task3_api' successfully
2025-03-11 16:53:09,598 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage api_gateway_resource, elapsed time: 0:00:00.005316
2025-03-11 16:53:18,778 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:53:20,988 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:53:22,558 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:53:22,558 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:53:22,933 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:53:22,933 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 16:53:22,934 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 16:53:22,935 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 16:53:22,936 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'api_gateway' in meta
2025-03-11 16:53:22,936 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': {'task3_api'}}' inside with type 'api_gateway'
2025-03-11 16:53:22,936 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for api_gateway 'task3_api' in meta...
2025-03-11 16:53:22,936 [INFO] USER:komal_agarwalla base_generator.py:106:_get_resource_meta_paths LOG: Found 'task3_api' in meta from 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found api_gateway 'task3_api' in these files: '['C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json']'
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla api_gateway_generator.py:53:get_meta_with_resource LOG: Found resource '/hello' in api 'task3_api' in file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla api_gateway_generator.py:258:write LOG: Adding method 'GET' to resource '/hello' to api 'task3_api'...
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla base_generator.py:115:_validate_lambda_existence LOG: Validating existence of lambda: hello_world
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla base_generator.py:121:_validate_lambda_existence LOG: Validation successfully finished, lambda exists
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 16:53:22,937 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value 'NONE' for param 'authorization_type'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value 'lambda' for param 'integration_type'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value 'hello_world' for param 'lambda_name'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object 'False' of the class '<class 'bool'>' for param 'api_key_required'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'method_request_parameters'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'integration_request_body_template'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'responses'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'integration_responses'
2025-03-11 16:53:22,938 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value 'True' for param 'default_error_pattern'
2025-03-11 16:53:22,939 [INFO] USER:komal_agarwalla meta.py:386:api_gateway_resource_method LOG: Method 'GET' was added to API gateway resource '/hello' successfully
2025-03-11 16:53:22,940 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage api_gateway_resource_method, elapsed time: 0:00:00.004675
2025-03-11 16:54:26,822 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:54:29,052 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:54:30,440 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:54:30,441 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:54:30,921 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:54:32,640 [INFO] USER:komal_agarwalla handlers.py:142:test LOG: Running tests...
2025-03-11 16:54:32,641 [INFO] USER:komal_agarwalla handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/komal_agarwalla/AWS/AWS/task03'.
2025-03-11 16:54:32,642 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.000967
2025-03-11 16:54:32,663 [INFO] USER:komal_agarwalla handlers.py:993:assemble LOG: Building artifacts, bundle: task03_250311.165430
2025-03-11 16:54:32,663 [INFO] USER:komal_agarwalla project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\jsrc\main\java\com\task03.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:400:_update_lambdas_from_path LOG: Going to add the following 'java' lambda:'hello_world' to the pending ProjectState.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\src\lambdas.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\app\lambdas.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\dnapp\lambdas.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\swagger_src.
2025-03-11 16:54:32,665 [INFO] USER:komal_agarwalla project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\komal_agarwalla\AWS\AWS\task03\appsync_src.
2025-03-11 16:54:32,667 [INFO] USER:komal_agarwalla handlers.py:718:assemble_java_mvn LOG: Command compile java project path: jsrc/main/java
2025-03-11 16:54:32,668 [INFO] USER:komal_agarwalla java.py:34:assemble_java_mvn_lambdas LOG: Java sources are located by path: C:/Users/komal_agarwalla/AWS/AWS/task03/jsrc/main/java
2025-03-11 16:54:32,668 [INFO] USER:komal_agarwalla java.py:35:assemble_java_mvn_lambdas LOG: Going to process java mvn project by path: C:/Users/komal_agarwalla/AWS/AWS/task03
2025-03-11 16:54:39,719 [INFO] USER:komal_agarwalla helper.py:107:execute_command_by_path LOG: Running the command "['C:\\Program Files\\apache-maven-3.9.9\\bin\\mvn.CMD', 'clean', 'install']"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< task03-group:task03 >-------------------------
[INFO] Building task03 1.0.0
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ task03 ---
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ task03 ---
[INFO] skip non existing resourceDirectory C:\Users\komal_agarwalla\AWS\AWS\task03\jsrc\main\resources
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ task03 ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 1 source file with javac [debug target 11] to target\classes
[WARNING] location of system modules is not set in conjunction with -source 11
  not setting the location of system modules may lead to class files that cannot run on JDK 11
    --release 11 is recommended instead of -source 11 -target 11 because it sets the location of system modules automatically
[INFO] 
[INFO] --- deployment-configuration:1.15.0:gen-deployment-config (generate-config) @ task03 ---
[WARNING] 1 problem was encountered while building the effective model for org.javassist:javassist:jar:3.19.0-GA during dependency collection step for plugin (use -X to see details)
[info] Start creating resources_config.json ...
[info] Path to deployment package ==> task03-1.0.0.jar
[debug] Creating custom classpath ...
[debug] Setting up new classloader ...
[INFO] 
[INFO] --- deployment-configuration:1.15.0:assemble-lambda-layer-files (generate-config) @ task03 ---
[info] Start creating resources_config.json ...
[info] Path to deployment package ==> task03-1.0.0.jar
[debug] Creating custom classpath ...
[debug] Setting up new classloader ...
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ task03 ---
[INFO] skip non existing resourceDirectory C:\Users\komal_agarwalla\AWS\AWS\task03\src\test\resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ task03 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ task03 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.4.1:jar (default-jar) @ task03 ---
[INFO] Building jar: C:\Users\komal_agarwalla\AWS\AWS\task03\target\task03-1.0.0.jar
[INFO] 
[INFO] --- shade:3.5.2:shade (default) @ task03 ---
[INFO] Including com.amazonaws:aws-lambda-java-core:jar:1.2.0 in the shaded jar.
[INFO] Including net.sf.aws-syndicate:deployment-configuration-annotations:jar:1.15.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.16.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.16.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.16.1 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] jackson-core-2.16.1.jar, jackson-databind-2.16.1.jar define 1 overlapping classes: 
[WARNING]   - META-INF.versions.9.module-info
[WARNING] jackson-annotations-2.16.1.jar, jackson-core-2.16.1.jar, jackson-databind-2.16.1.jar define 2 overlapping resources: 
[WARNING]   - META-INF/LICENSE
[WARNING]   - META-INF/NOTICE
[WARNING] aws-lambda-java-core-1.2.0.jar, deployment-configuration-annotations-1.15.0.jar, jackson-annotations-2.16.1.jar, jackson-core-2.16.1.jar, jackson-databind-2.16.1.jar, task03-1.0.0.jar define 1 overlapping resource: 
[WARNING]   - META-INF/MANIFEST.MF
[WARNING] maven-shade-plugin has detected that some files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the file is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See https://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\komal_agarwalla\AWS\AWS\task03\target\task03-1.0.0.jar with C:\Users\komal_agarwalla\AWS\AWS\task03\target\task03-1.0.0-shaded.jar
[INFO] 
[INFO] --- install:3.1.2:install (default-install) @ task03 ---
[INFO] Installing C:\Users\komal_agarwalla\AWS\AWS\task03\pom.xml to C:\Users\komal_agarwalla\.m2\repository\task03-group\task03\1.0.0\task03-1.0.0.pom
[INFO] Installing C:\Users\komal_agarwalla\AWS\AWS\task03\target\task03-1.0.0.jar to C:\Users\komal_agarwalla\.m2\repository\task03-group\task03\1.0.0\task03-1.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.733 s
[INFO] Finished at: 2025-03-11T16:54:39+05:30
[INFO] ------------------------------------------------------------------------


2025-03-11 16:54:39,736 [INFO] USER:komal_agarwalla java.py:53:assemble_java_mvn_lambdas LOG: Java mvn project was processed successfully
2025-03-11 16:54:39,736 [INFO] USER:komal_agarwalla handlers.py:729:assemble_java_mvn LOG: Java artifacts were prepared successfully.
2025-03-11 16:54:39,737 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage assemble_java_mvn, elapsed time: 0:00:07.069942
2025-03-11 16:54:39,739 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:07.075870
2025-03-11 16:54:39,741 [INFO] USER:komal_agarwalla handlers.py:1037:package_meta LOG: Package meta, bundle: task03_250311.165430
2025-03-11 16:54:39,741 [INFO] USER:komal_agarwalla meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/komal_agarwalla/AWS/AWS/task03/bundles/task03_250311.165430
2025-03-11 16:54:39,745 [INFO] USER:komal_agarwalla helper.py:292:write_content_to_file LOG: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev/bundles/task03_250311.165430\build_meta.json file was created.
2025-03-11 16:54:39,749 [INFO] USER:komal_agarwalla handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-11 16:54:39,749 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.008333
2025-03-11 16:54:40,741 [INFO] USER:komal_agarwalla handlers.py:1083:upload LOG: Upload bundle: task03_250311.165430
2025-03-11 16:54:41,979 [INFO] USER:komal_agarwalla bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-11 16:54:50,141 [INFO] USER:komal_agarwalla handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-11 16:54:50,141 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:10.390125
2025-03-11 16:54:50,147 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage build, elapsed time: 0:00:19.224680
2025-03-11 16:55:03,875 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 16:55:06,078 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 16:55:07,568 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:07,569 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:07,988 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:55:08,356 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:08,356 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:08,860 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:55:08,860 [INFO] USER:komal_agarwalla helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task03
2025-03-11 16:55:09,391 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:09,392 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:10,132 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:55:10,132 [INFO] USER:komal_agarwalla helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task03_250311.165430
2025-03-11 16:55:10,474 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:10,475 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:10,858 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:55:11,237 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:11,238 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:11,586 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 16:55:13,705 [INFO] USER:komal_agarwalla deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-11 16:55:13,706 [INFO] USER:komal_agarwalla deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-11 16:55:14,036 [INFO] USER:komal_agarwalla deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-11 16:55:16,078 [INFO] USER:komal_agarwalla iam_resource.py:120:_create_policy_from_meta LOG: Created IAM policy cmtr-15c0cefe-lambda-basic-execution.
2025-03-11 16:55:16,384 [INFO] USER:komal_agarwalla deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-11 16:55:23,319 [INFO] USER:komal_agarwalla iam_resource.py:183:_create_role_from_meta LOG: Created IAM role cmtr-15c0cefe-HelloWorld-role.
2025-03-11 16:55:24,413 [INFO] USER:komal_agarwalla iam_resource.py:183:_create_role_from_meta LOG: Created IAM role cmtr-15c0cefe-hello_world-role.
2025-03-11 16:55:24,414 [INFO] USER:komal_agarwalla deployment_processor.py:74:_process_resources LOG: Processing lambda resources
2025-03-11 16:55:29,513 [INFO] USER:komal_agarwalla lambda_resource.py:1394:_resolve_log_group LOG: Cloud Watch log group for lambda: cmtr-15c0cefe-hello_world does not exists. Creating new log group with name: aws/lambda/cmtr-15c0cefe-hello_world
2025-03-11 16:55:30,818 [INFO] USER:komal_agarwalla deployment_processor.py:88:_process_resources LOG: Processing api_gateway resources
2025-03-11 16:55:31,820 [WARNING] USER:komal_agarwalla api_gateway_connection.py:160:get_api_by_name LOG: API Gateway with the name "cmtr-15c0cefe-task3_api" not found in the region eu-west-1
2025-03-11 16:55:31,821 [INFO] USER:komal_agarwalla api_gateway_resource.py:372:_create_api_gateway_from_meta LOG: Api gateway with name 'cmtr-15c0cefe-task3_api' does not exist. Creating
2025-03-11 16:55:33,825 [INFO] USER:komal_agarwalla api_gateway_resource.py:717:__prepare_api_resources_args LOG: Creating resource /hello ...
2025-03-11 16:55:34,471 [INFO] USER:komal_agarwalla api_gateway_resource.py:824:_create_resource_from_metadata LOG: Resource /hello created.
2025-03-11 16:55:34,685 [INFO] USER:komal_agarwalla api_gateway_resource.py:835:_create_resource_from_metadata LOG: Creating method GET for resource /hello...
2025-03-11 16:55:36,313 [INFO] USER:komal_agarwalla api_gateway_resource.py:852:_create_resource_from_metadata LOG: Method GET for resource /hello created.
2025-03-11 16:55:46,761 [INFO] USER:komal_agarwalla api_gateway_resource.py:297:configure_resources LOG: Throttling for /hello disabled.
2025-03-11 16:55:47,079 [INFO] USER:komal_agarwalla api_gateway_resource.py:354:configure_resources LOG: Resource /hello was configured
2025-03-11 16:55:47,521 [INFO] USER:komal_agarwalla api_gateway_resource.py:756:describe_api_resources LOG: Described cmtr-15c0cefe-task3_api API Gateway.
2025-03-11 16:55:47,522 [INFO] USER:komal_agarwalla deployment_processor.py:540:create_deployment_resources LOG: AWS resources were deployed successfully
2025-03-11 16:55:47,522 [INFO] USER:komal_agarwalla deployment_processor.py:543:create_deployment_resources LOG: Going to apply dynamic changes
2025-03-11 16:55:47,522 [INFO] USER:komal_agarwalla deployment_processor.py:545:create_deployment_resources LOG: Dynamic changes were applied successfully
2025-03-11 16:55:47,522 [INFO] USER:komal_agarwalla deployment_processor.py:547:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-11 16:55:47,550 [INFO] USER:komal_agarwalla group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-11 16:55:47,550 [INFO] USER:komal_agarwalla deployment_processor.py:550:create_deployment_resources LOG: Going to create deploy output
2025-03-11 16:55:48,881 [INFO] USER:komal_agarwalla bundle_processor.py:71:create_deploy_output LOG: Output file with name task03_250311.165430/outputs/task03.json has been created
2025-03-11 16:55:48,881 [INFO] USER:komal_agarwalla deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task03 was created.
2025-03-11 16:55:48,882 [INFO] USER:komal_agarwalla handlers.py:347:deploy LOG: Backend resources were deployed.
2025-03-11 16:55:48,882 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:37.295819
2025-03-11 16:55:49,245 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 16:55:49,245 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 16:55:49,610 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:15:45,417 [INFO] USER:komal_agarwalla generate.py:72:project LOG: Project name: task04
2025-03-11 17:15:45,419 [INFO] USER:komal_agarwalla generate.py:79:project LOG: Project path: C:\Users\komal_agarwalla\AWS\AWS\task03
2025-03-11 17:15:45,443 [INFO] USER:komal_agarwalla project.py:77:generate_project_structure LOG: Project task04 folder has been successfully created.
2025-03-11 17:15:45,443 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage project, elapsed time: 0:00:00.025820
2025-03-11 17:16:03,804 [INFO] USER:komal_agarwalla s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-8660'
2025-03-11 17:16:03,805 [INFO] USER:komal_agarwalla s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-8660'
2025-03-11 17:16:03,805 [INFO] USER:komal_agarwalla helper.py:525:convert LOG: Stripping run_id:JAP-09,run_type:stm,type:user,user_id:15c0cefe from "," a bit..
2025-03-11 17:16:03,805 [INFO] USER:komal_agarwalla helper.py:529:convert LOG: Converting: run_id:JAP-09,run_type:stm,type:user,user_id:15c0cefe to dict..
2025-03-11 17:16:03,805 [INFO] USER:komal_agarwalla helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-09', 'run_type': 'stm', 'type': 'user', 'user_id': '15c0cefe'}
2025-03-11 17:16:05,520 [WARNING] USER:komal_agarwalla generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-11 17:16:05,521 [ERROR] USER:komal_agarwalla __init__.py:44:_mkdir LOG: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\.syndicate-config-dev'
2025-03-11 17:16:05,537 [WARNING] USER:komal_agarwalla generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:16:05,541 [INFO] USER:komal_agarwalla generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:16:05,542 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage config, elapsed time: 0:00:01.736792
2025-03-11 17:27:55,426 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:27:57,664 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 17:27:59,195 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:27:59,196 [INFO] USER:komal_agarwalla helper.py:658:check_lambda_name LOG: Validating lambda name: 'SQS'
2025-03-11 17:27:59,196 [INFO] USER:komal_agarwalla helper.py:673:check_lambda_name LOG: Lambda name: 'SQS' passed the validation
2025-03-11 17:27:59,196 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 17:27:59,197 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 17:28:32,738 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:28:34,949 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 17:28:36,304 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 17:28:36,304 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 17:28:36,715 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:28:36,715 [INFO] USER:komal_agarwalla helper.py:658:check_lambda_name LOG: Validating lambda name: 'sqs_handler'
2025-03-11 17:28:36,715 [INFO] USER:komal_agarwalla helper.py:673:check_lambda_name LOG: Lambda name: 'sqs_handler' passed the validation
2025-03-11 17:28:36,716 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 17:28:36,716 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 17:28:36,717 [INFO] USER:komal_agarwalla generate.py:116:lambda_function LOG: Lambda names: ('sqs_handler',)
2025-03-11 17:28:36,717 [INFO] USER:komal_agarwalla generate.py:117:lambda_function LOG: Runtime: java
2025-03-11 17:28:36,718 [INFO] USER:komal_agarwalla generate.py:118:lambda_function LOG: Project path: C:/Users/komal_agarwalla/AWS/AWS/task03
2025-03-11 17:28:36,724 [INFO] USER:komal_agarwalla project.py:97:_generate_java_project_hierarchy LOG: Pom file inside C:/Users/komal_agarwalla/AWS/AWS/task03 already exists
2025-03-11 17:28:36,727 [INFO] USER:komal_agarwalla lambda_function.py:374:_generate_java_lambdas LOG: Lambda sqs_handler created
2025-03-11 17:28:36,733 [INFO] USER:komal_agarwalla lambda_function.py:169:generate_lambda_function LOG: Lambda sqs_handler has been successfully added to the project.
2025-03-11 17:28:36,734 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage lambda_function, elapsed time: 0:00:00.017219
2025-03-11 17:31:48,604 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:31:50,845 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 17:31:52,165 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 17:31:52,165 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 17:31:52,524 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:31:52,524 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 17:31:52,525 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 17:34:26,726 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:34:28,968 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 17:34:30,300 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 17:34:30,300 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 17:34:30,805 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:34:30,805 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 17:34:30,806 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 17:34:30,807 [INFO] USER:komal_agarwalla base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'async_queue'
2025-03-11 17:34:30,807 [INFO] USER:komal_agarwalla base_generator.py:239:_validate_resource_name LOG: Resource name: 'async_queue' passed the validation
2025-03-11 17:34:30,807 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 17:34:30,809 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'sqs_queue' in meta
2025-03-11 17:34:30,809 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': set(), 'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\task04\\deployment_resources.json': set()}' inside with type 'sqs_queue'
2025-03-11 17:34:30,809 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for sqs_queue 'async_queue' in meta...
2025-03-11 17:34:30,809 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found sqs_queue 'async_queue' in these files: '[]'
2025-03-11 17:34:30,810 [INFO] USER:komal_agarwalla base_generator.py:217:_find_file_with_duplicate LOG: No duplicated sqs_queue with name 'async_queue' was found
2025-03-11 17:34:30,810 [INFO] USER:komal_agarwalla base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for sqs_queue 'async_queue'
2025-03-11 17:34:30,810 [INFO] USER:komal_agarwalla base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for sqs_queue 'async_queue'
2025-03-11 17:34:30,810 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object 'False' of the class '<class 'bool'>' for param 'fifo_queue'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value '300' for param 'visibility_timeout'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value '0' for param 'delay_seconds'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value '1024' for param 'maximum_message_size'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value '60' for param 'message_retention_period'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value '0' for param 'receive_message_wait_time_seconds'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'policy'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:53:_resolve_configuration LOG: Setting default value 'False' for param 'content_based_deduplication'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-11 17:34:30,811 [INFO] USER:komal_agarwalla base_generator.py:202:write LOG: Writing deployment resources for sqs_queue 'async_queue' to the file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 17:34:30,812 [INFO] USER:komal_agarwalla meta.py:687:sqs_queue LOG: SQS queue 'async_queue' was added successfully
2025-03-11 17:34:30,813 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage sqs_queue, elapsed time: 0:00:00.006247
2025-03-11 17:34:57,774 [INFO] USER:komal_agarwalla handlers.py:106:syndicate LOG: Configuration used: C:\Users\komal_agarwalla\AWS\AWS\task03\.syndicate-config-dev
2025-03-11 17:34:59,996 [INFO] USER:komal_agarwalla processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-11 17:35:01,356 [INFO] USER:komal_agarwalla project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-11 17:35:01,356 [INFO] USER:komal_agarwalla project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-11 17:35:01,745 [INFO] USER:komal_agarwalla sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-11 17:35:01,746 [INFO] USER:komal_agarwalla helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-11 17:35:01,746 [INFO] USER:komal_agarwalla helper.py:651:resolve_project_path LOG: Path: 'C:/Users/komal_agarwalla/AWS/AWS/task03' was assigned to the parameter: 'project_path'
2025-03-11 17:35:01,747 [INFO] USER:komal_agarwalla helper.py:503:convert LOG: Checking whether eu-west-1 is a valid region...
2025-03-11 17:35:01,747 [INFO] USER:komal_agarwalla helper.py:508:convert LOG: Value 'eu-west-1' is a valid region, returning..
2025-03-11 17:35:01,747 [INFO] USER:komal_agarwalla base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'lambda_topic'
2025-03-11 17:35:01,748 [INFO] USER:komal_agarwalla base_generator.py:239:_validate_resource_name LOG: Resource name: 'lambda_topic' passed the validation
2025-03-11 17:35:01,748 [INFO] USER:komal_agarwalla base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/komal_agarwalla/AWS/AWS/task03'
2025-03-11 17:35:01,750 [INFO] USER:komal_agarwalla base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'sns_topic' in meta
2025-03-11 17:35:01,750 [INFO] USER:komal_agarwalla base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\deployment_resources.json': set(), 'C:\\Users\\komal_agarwalla\\AWS\\AWS\\task03\\task04\\deployment_resources.json': set()}' inside with type 'sns_topic'
2025-03-11 17:35:01,750 [INFO] USER:komal_agarwalla base_generator.py:103:_get_resource_meta_paths LOG: Looking for sns_topic 'lambda_topic' in meta...
2025-03-11 17:35:01,750 [INFO] USER:komal_agarwalla base_generator.py:108:_get_resource_meta_paths LOG: Found sns_topic 'lambda_topic' in these files: '[]'
2025-03-11 17:35:01,751 [INFO] USER:komal_agarwalla base_generator.py:217:_find_file_with_duplicate LOG: No duplicated sns_topic with name 'lambda_topic' was found
2025-03-11 17:35:01,751 [INFO] USER:komal_agarwalla base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for sns_topic 'lambda_topic'
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for sns_topic 'lambda_topic'
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:57:_resolve_configuration LOG: Setting given value 'eu-west-1' for param 'region'
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'event_sources'
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-11 17:35:01,752 [INFO] USER:komal_agarwalla base_generator.py:202:write LOG: Writing deployment resources for sns_topic 'lambda_topic' to the file 'C:\Users\komal_agarwalla\AWS\AWS\task03\deployment_resources.json'
2025-03-11 17:35:01,753 [INFO] USER:komal_agarwalla meta.py:489:sns_topic LOG: SNS topic 'lambda_topic' was added successfully
2025-03-11 17:35:01,753 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage sns_topic, elapsed time: 0:00:00.005730
2025-03-11 17:37:33,259 [INFO] USER:komal_agarwalla generate.py:72:project LOG: Project name: task04
2025-03-11 17:37:33,259 [INFO] USER:komal_agarwalla generate.py:79:project LOG: Project path: C:\Users\komal_agarwalla\AWS\AWS
2025-03-11 17:37:33,282 [INFO] USER:komal_agarwalla project.py:77:generate_project_structure LOG: Project task04 folder has been successfully created.
2025-03-11 17:37:33,283 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage project, elapsed time: 0:00:00.023745
2025-03-11 17:38:15,280 [INFO] USER:komal_agarwalla s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-8660'
2025-03-11 17:38:15,281 [INFO] USER:komal_agarwalla s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-8660'
2025-03-11 17:38:15,281 [INFO] USER:komal_agarwalla helper.py:525:convert LOG: Stripping run_id:JAP-09,run_type:stm,type:user,user_id:15c0cefe from "," a bit..
2025-03-11 17:38:15,281 [INFO] USER:komal_agarwalla helper.py:529:convert LOG: Converting: run_id:JAP-09,run_type:stm,type:user,user_id:15c0cefe to dict..
2025-03-11 17:38:15,281 [INFO] USER:komal_agarwalla helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-09', 'run_type': 'stm', 'type': 'user', 'user_id': '15c0cefe'}
2025-03-11 17:38:17,130 [WARNING] USER:komal_agarwalla generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-11 17:38:17,131 [WARNING] USER:komal_agarwalla generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\komal_agarwalla\AWS\AWS\task04\.syndicate-config-dev
2025-03-11 17:38:17,136 [INFO] USER:komal_agarwalla generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\komal_agarwalla\AWS\AWS\task04\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\komal_agarwalla\AWS\AWS\task04\.syndicate-config-dev
2025-03-11 17:38:17,138 [INFO] USER:komal_agarwalla helper.py:330:timed LOG: Stage config, elapsed time: 0:00:01.856891
